"""v4

Revision ID: 20250107_v4
Revises: 20241210_v2
Create Date: 2025-01-07 13:11:08.607096+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250107_v4'
down_revision = '20241210_v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=100), nullable=False),
    sa.Column('rok_vydani', sa.Integer(), nullable=False),
    sa.Column('popis_filmu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmy')
    # ### end Alembic commands ###
